#!/usr/bin/env ruby

class Main
	def initialize
    @user = `whoami`
    @system = `uname -n`
    @kernel = `uname -r`
    @up = (`uptime -p`)

     
    puts "User: #{@user}"
    puts "OS: #{@system}"
    puts "Kernel: #{@kernel}"
    puts "Uptime: #{@up}"

  end
end

Main.new
