#!/usr/bin/env ruby

class Main
	def initialize

    @user = `whoami`
    @hostname = `hostname`
    @sys = `uname -n`
    @kernel = `uname -r`
    @up = (`uptime -p`)

    show

  end
  
  def show
    show_information = <<-herend

                  ##                   #{@user.strip}@#{@hostname.strip}
                 ####                  --------------------------
                ######                 User:   #{@user.strip}
               ########                OS:     #{@sys.strip}
              ##########               Kernel: #{@kernel.strip}
             ############              Uptime: #{@up.strip}
            ##############
           ################
          ##################
         ####################
        ######################
       #########      #########
      ##########      ##########
     ###########      ###########
    ##########          ##########
   #######                  #######
  ####                          ####
 ###                              ###

herend
  puts show_information
  end

end

Main.new
